/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const defineLocale: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internationalized+date@3.12.1_@internationalized+number@3.6.6_@tiptap+e_bbb5f884080d6f68014d1566d1b081b5/node_modules/@nuxt/ui/dist/runtime/composables/defineLocale').defineLocale
  const defineShortcuts: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internationalized+date@3.12.1_@internationalized+number@3.6.6_@tiptap+e_bbb5f884080d6f68014d1566d1b081b5/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts').defineShortcuts
  const extendLocale: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internationalized+date@3.12.1_@internationalized+number@3.6.6_@tiptap+e_bbb5f884080d6f68014d1566d1b081b5/node_modules/@nuxt/ui/dist/runtime/composables/defineLocale').extendLocale
  const extractShortcuts: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internationalized+date@3.12.1_@internationalized+number@3.6.6_@tiptap+e_bbb5f884080d6f68014d1566d1b081b5/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts').extractShortcuts
  const useAppConfig: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internationalized+date@3.12.1_@internationalized+number@3.6.6_@tiptap+e_bbb5f884080d6f68014d1566d1b081b5/node_modules/@nuxt/ui/dist/runtime/vue/composables/useAppConfig.js').useAppConfig
  const useContentSearch: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internationalized+date@3.12.1_@internationalized+number@3.6.6_@tiptap+e_bbb5f884080d6f68014d1566d1b081b5/node_modules/@nuxt/ui/dist/runtime/composables/useContentSearch').useContentSearch
  const useFileUpload: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internationalized+date@3.12.1_@internationalized+number@3.6.6_@tiptap+e_bbb5f884080d6f68014d1566d1b081b5/node_modules/@nuxt/ui/dist/runtime/composables/useFileUpload').useFileUpload
  const useFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internationalized+date@3.12.1_@internationalized+number@3.6.6_@tiptap+e_bbb5f884080d6f68014d1566d1b081b5/node_modules/@nuxt/ui/dist/runtime/composables/useFormField').useFormField
  const useKbd: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internationalized+date@3.12.1_@internationalized+number@3.6.6_@tiptap+e_bbb5f884080d6f68014d1566d1b081b5/node_modules/@nuxt/ui/dist/runtime/composables/useKbd').useKbd
  const useOverlay: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internationalized+date@3.12.1_@internationalized+number@3.6.6_@tiptap+e_bbb5f884080d6f68014d1566d1b081b5/node_modules/@nuxt/ui/dist/runtime/composables/useOverlay').useOverlay
  const useResizable: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internationalized+date@3.12.1_@internationalized+number@3.6.6_@tiptap+e_bbb5f884080d6f68014d1566d1b081b5/node_modules/@nuxt/ui/dist/runtime/composables/useResizable').useResizable
  const useScrollShadow: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internationalized+date@3.12.1_@internationalized+number@3.6.6_@tiptap+e_bbb5f884080d6f68014d1566d1b081b5/node_modules/@nuxt/ui/dist/runtime/composables/useScrollShadow').useScrollShadow
  const useScrollspy: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internationalized+date@3.12.1_@internationalized+number@3.6.6_@tiptap+e_bbb5f884080d6f68014d1566d1b081b5/node_modules/@nuxt/ui/dist/runtime/composables/useScrollspy').useScrollspy
  const useToast: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internationalized+date@3.12.1_@internationalized+number@3.6.6_@tiptap+e_bbb5f884080d6f68014d1566d1b081b5/node_modules/@nuxt/ui/dist/runtime/composables/useToast').useToast
}
